#!/usr/bin/env bash

printf "\nCurrent directory: '$(pwd)'\n"

if [[ $# -ne 4 ]]; then
  printf "\nERROR: There should be exactly 4 arguments\n"
  printf " * an input '.csv' file containing the experiment data\n"
  printf " * an input '.yaml' file containing the experiment info (testbed, conditions, etc...)\n"
  printf " * an input '.yaml' file containing the subject info\n"
  printf " * an output directory where the results is stored\n\n"
  printf "Usage example:\n"
  printf " ./run_local_pi exp_csv_file_path exp_yaml_file_path subject_yaml_file_path output_dir_path\n"
  exit 127
fi

printf "Experiment data input file: '$1'\n"
printf "Experiment info input file: '$2'\n"
printf "Subject info input file: '$3'\n"
printf "Output directory: '$4'\n\n"

matlab -sd "./" -batch "run_local_pi('$1', '$2', '$3', '$4')"