#!/usr/bin/env bash

printf "\nCurrent directory: '$(pwd)'\n"

if [[ $# -ne 3 ]]; then
  printf "\nERROR: There should be exactly 3 arguments\n"
  printf " * an input directory containing all the data of the tested subject\n"
  printf " * an integer which identifies the protocol to be evaluated:\n"
  printf "    1) Impulsive Disturbance\n"
  printf "    2) Sinusiodal Displacement Disturbance\n"
  printf "    3) Sinusoidal Force Disturbance\n"
  printf "    4) Quasi_static Displacement Disturbance\n"
  printf "    5) Quasi-static Force Disturbance\n"
  printf " * an output directory where the results is stored\n\n"
  printf "Usage example:\n"
  printf " ./run_global_pi input_dir_path protocol_num output_dir_path\n"
  exit 127
fi

printf "Input directory: '$1'\n"
printf "Input protocol number: '$2'\n"
printf "Output directory: '$3'\n\n"

matlab -sd "./" -batch "run_global_pi('$1', '$2', '$3')"