protocol:
  id: "1"  # The integer unique identifier used for data storage
  name: "impulsive_disturbance"  # The identifier of the protocol to be used in the current experiment
  notes: ""  # Some relevant notes regarding the experiment setup
  repetitions: 3  # The number of repetitions of the experiment
  parameters:
    id: "000"  # The integer unique identifier used for data storage
    initial_energy: 0.0  # The initial energy which determines the initial pendulum position [J]
    impact_force: 0.0 # The desired impact force [N]